spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    data: classpath:/db/data/data.sql
  application:
    name: foodfanda
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  h2:
    console:
      enabled: true
server:
  port: 8082
  servlet:
    context-path: /foodfanda

logging:
  level:
    root:
      org.springframework.web: INFO
      org.hibernate: INFO

